CREATE TABLE row (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  template_pixel_art_id INT NOT NULL,
  create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (template_pixel_art_id) REFERENCES template_pixel_art (id)
  ON DELETE CASCADE ON UPDATE CASCADE
);
